FROM rustlang/rust:nightly-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    pkg-config \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV RUST_LOG=info

CMD ["cargo", "run"]
